component: aws-dynamodb
name: database
inputs:
  name: ${name}-${stage}
  region: ap-south-1
  # Don't delete the Database Table if "serverless remove" is run
  deletionPolicy: retain
  # Simple, single-table design
  attributeDefinitions:
    - AttributeName: Email
      AttributeType: S
    - AttributeName: Phoneno
      AttributeType: S
  keySchema:
    - AttributeName: Email
      KeyType: HASH
    - AttributeName: Phoneno
      KeyType: RANGE
  globalSecondaryIndexes:
    - IndexName: gsi1
      KeySchema:
        - AttributeName: Phoneno
          KeyType: HASH
        - AttributeName: Email
          KeyType: RANGE
      Projection:
        ProjectionType: ALL
