version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-putS3file"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kgunfkf8sxw7"
s3_prefix = "lambda-putS3file"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["HelloWorldFunction=052244742307.dkr.ecr.ap-northeast-1.amazonaws.com/lambdaputs3file36761fa3/helloworldfunction19d43fc4repo"]
